//
//  ContentView.swift
//  CurrencyConverter
//
//  Created by Pushpank Kumar on 25/01/25.
//

import SwiftUI
import CoreData

struct CurrencyConverterDashboardView: View {
    
    @StateObject private var viewModel = CurrencyViewModel()
    @State private var selectedCurrency: Currency = .init()
    let columns = [GridItem(.adaptive(minimum: 100))]
    
    var body: some View {
        NavigationView {
            ScrollView {
                VStack {
                    amountTextField
                    if viewModel.isLoading {
                        ProgressView()
                            .padding()
                    } else {
                        CurrencySelectionView(viewModel: viewModel)
                        CurrencyRatesView(viewModel: viewModel, columns: columns)
                    }
                }
                .padding()
            }
            .onAppear {
                Task {
                    await viewModel.fetchData()
                }
            }// If you use SwiftGen or Tuist, these strings can be autogenerated, so there’s no chance of a spelling mismatch.
            .navigationTitle(String(localized: "Currency Converter"))
        }
    }
    
    @ViewBuilder private var amountTextField: some View {
        HStack {
            TextField(String(localized: "Enter amount"), text: $viewModel.inputAmount)
        }
        .keyboardType(.numberPad)
        .padding()
        .background(Color.theme.background)
        .cornerRadius(15)
    }
}

#Preview {
    CurrencyConverterDashboardView()
}
