# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
	lane :register_app do
		produce(
			username: "pushpankq@gmail.com",
			app_identifier: "com.state.CurrencyConverter",
			app_name: "Currency converter",
			team_name: "Pushpank Kumar",
			itc_team_name: "Pushpank Kumar"
		)
  	end

  	lane :get_dev_certs do
		cert(development: true)
		sigh(development: true)
	end

  	lane :sync_all_development do
		match(type: "development")
	end
end
